# Generated by Django 5.0.3 on 2024-03-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerregestration',
            table=None,
        ),
    ]
